/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tbernard' at '16/08/14 2:29 PM' with Gradle 2.0
 *
 * @author tbernard, @date 16/08/14 2:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
